### ISSUE TITLE
Projects Discovery Of Handwashing R - Correct answer is not accepted.

### ISSUE THREAD

**Issue by ncarchedi** [datacamp/projects-discovery-of-handwashing-r#10]
@kasthynguyen commented on [Sat Jul 14 2018](https://github.com/datacamp/learn-bugs/issues/314)

### Summary of the issue

Projects Discovery Of Handwashing R - Test 5
It seems like the correct answer is not accepted. I tried two answers but none of it works. 

<img width="924" alt="screenshot" src="https://user-images.githubusercontent.com/23623241/42726797-6dfe15fc-87c4-11e8-9d9f-3813ac790d87.png">
<img width="921" alt="screenshot" src="https://user-images.githubusercontent.com/23623241/42726810-b262eae2-87c4-11e8-8410-899107ebd965.png">

Link to the location of the error: https://projects.datacamp.com/projects/49

User ID: 2073368

<div style="background-color:#BBDEFB;padding:10px;border-radius:5px;" id="zdArea">                             	                                                              <div style="text-decoration:underline;margin-bottom:5px;color:#00000082;" id="zd-ReservedAreaHeader">                 <span class="zdDescription" style="font-weight: bold;"><h3 style="margin:0px;padding:0px;">Zendesk Information</h3></span>                 <div class="zdValue"></div>             </div>                          <div class="ValueTypeField" style id="zd-TicketLinkUpdateIssue"><span style="margin-right:5px;">&#9679;</span>                 <span class="zdDescription" style="font-weight: bold;">Linked with zendesk ticket:</span>                 <span class="zdValue"><a href="https://datacamp.zendesk.com/agent/tickets/107096" target="_blank">107096</a></span>             </div>             </div>

**Comment by davidventuri** [comment]
@kasthynguyen @ncarchedi This was indeed a Project tests* issue. The instructor fixed this issue in this pull request that I just merged to master and the live Project. I have tested both solutions depicted in the image above and they both work.

*Note I didn't use the term SCT, on advice from @filipsch:

<img width="669" alt="screenshot 2018-07-16 18 53 10" src="https://user-images.githubusercontent.com/15305603/42787687-999eda5a-8929-11e8-8b9d-4cd3a7691968.png">
