### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by davidventuri** [datacamp/projects-discovery-of-handwashing-r#11]
There is a minor typo in the tests for Task 7. _"containt"_ should be _"contain"_.

```'monthly_summary should containt the mean monthly proportion of deaths before and after handwashing was enforced.'```

**Comment by rasmusab** [comment]
This has been fixed in commit https://github.com/datacamp/projects-discovery-of-handwashing-r/commit/b7f8018c42dd40a03e3c22e8a1eddcc88558e3be .
