### ISSUE TITLE
Test number 6

### ISSUE THREAD

**Issue by bbevan** [datacamp/projects-discovery-of-handwashing-r#6]
Hello,

please note that if a student accidentally plots with the command 

```{r}
ggplot(monthly, aes(x = date, y = proportion_deaths, color = handwashing_started)) +
  geom_line()
```

instead of 

```{r}
ggplot(monthly, aes(x = date, y = proportion_deaths, colour = handwashing_started)) +
  geom_line()
```

then the test will not pass and they will not be able to complete the project on DataCamp.

**Comment by rasmusab** [comment]
@davidventuri ,

This should be addressed in this pull request: https://github.com/datacamp/projects-discovery-of-handwashing-r/pull/9

Please tag me in further issues :)

/Rasmus
