### ISSUE TITLE
Test number 5

### ISSUE THREAD

**Issue by rafaelcharris** [datacamp/projects-discovery-of-handwashing-r#7]
Note that in test 5 if a student use:
`ggplot(monthly) + 
        geom_line(aes(x = date, y = proportion_deaths)) + 
        labs(x = "date", y = "proportion of deaths")`

instead of

`ggplot(monthly, aes(x = date, y = proportion_deaths)) + 
        geom_line() + 
        labs(x = "date", y = "proportion of deaths")`

It would be considered as a mistake and the student would not be able to finish the project.

**Comment by rasmusab** [comment]
@davidventuri ,

This should be addressed in this pull request: https://github.com/datacamp/projects-discovery-of-handwashing-r/pull/9

Please tag me in further issues :)

/Rasmus

**Comment by jonny83** [comment]
Well, it seems now the problem has changed.  for both commands I am getting an error message!

**Comment by rasmusab** [comment]
For me one of the solutions work, but you are correct that the second one doesn't. I've submitted a fix in the fix-rasmus branch, but as usual my commits seem cursed as I get the non-descript error:

![image](https://user-images.githubusercontent.com/1006144/45847397-311c9400-bd2b-11e8-99e1-762788501369.png)

@davidventuri It seems like I get this error almost _every time_ I try to change something in almost all old Projects. Any tip from teach/learn on how to avoid this error going forward would be a timesaver! :)

/Rasmus
